name: ptt
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geopandas
  - geopy
  - geoviews
  - hvplot
  - matplotlib
  - movingpandas
  - networkx
  - numpy
  - osmnx
  - pandas
  - shapely
