name: ptt
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cartopy
  - cython
  - geopandas
  - geopy
  - geoviews
  - hvplot
  - matplotlib
  - movingpandas
  - networkx
  - numpy
  - osmnx
  - pandas
  - panel
  - shapely
  - stonesoup
